### ISSUE TITLE
I think you need to rename your resume in header.html

### ISSUE THREAD

**Issue by alpiepho** [Alex-Cannon/alex-cannon.github.io#35]
You inspired me to try Jekyll and I was looking at your site, and noticed your resume link is failing.

Looks like the link in header.html is referencing a camel case .docx file, while your resume file is lowercase .pdf.

**Comment by Alex-Cannon** [comment]
@alpiepho Thanks for the heads up! Recently, I swapped my resume over to a .pdf file. I updated the resume button, but not the resume link in the navbar. Fixed with alex-cannon-35.
